export enum FilerType {
  Csr             = 0,
  PoId            = 1,
  RetailerPoId    = 2,
  Customer        = 3,
  DesignName      = 4,
  PartnerStyle    = 5,
  OrderDateFrom   = 6,
  OrderDateTo     = 7,
  StartDateFrom   = 8,
  StartDateTo     = 9,
  CancelDateFrom  = 10,
  CancelDateTo    = 11,
  ShipDateFrom    = 12,
  ShipDateTo      = 13,
  ColsName        = 14,
  ColStatus       = 15,
  ItemType        = 16,
  FulfillmentType = 17,
  ExcludeSmpl     = 18
}
